sudo: true
os: trusty
cache: false

env:
- URL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz

before_install:
- export SFDX_AUTOUPDATE_DISABLE=false
- export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
- export SFDX_DOMAIN_RETRY=300
- export SFDX_DISABLE_APP_HUB=true
- export SFDX_LOG_LEVEL=DEBUG
- mkdir sfdx
- wget -qO- $URL | tar xJ -C sfdx --strip-components 1
- "./sfdx/install"
- export PATH=./sfdx/$(pwd):$PATH
- sfdx --version
- sfdx plugins --core
- sfdx force:auth:jwt:grant --clientid 3MVG9KsVczVNcM8wazkGcZ1u7YplZe2a5OCXxKpdTwfB17Fo8ppFuKOqG2SZrkgVJ4JMffoEMJWLvdvXERBVi --jwtkeyfile assets/server.key --username ra.tien@curious-raccoon-awy5eo.com --setdefaultdevhubusername -a HubOrg
#script para rodar quando vier da branch de developer
if [ "$TRAVIS_BRANCH" == "Developer" ]; then
script:
- sfdx force:source:convert --rootdir force-app --outputdir tmp_convert
- jar -cfM release.zip tmp_convert
- rm -rf tmp_convert
- sfdx force:mdapi:deploy -w -1 --zipfile release.zip --targetusername ra.tien@curious-raccoon-awy5eo.com 
- rm -rf release.zip
fi;